// chains.config.js

const chains = [
  // ─── HOT WALLET CHAINS (funded later) ───────────────────────────────────
  {
    id: "sepolia",
    name: "Sepolia",
    type: "hotwallet",
    comingSoon: true,
    enabled: true,
    walletAddress: "0xf760589E8adBf622A49fB9F47983777a2963Bd43",
    privateKeyEnv: "SEPOLIA_PRIVATE_KEY",
    rpcUrl: process.env.SEPOLIA_RPC_URL,
    chainId: 11155111,
    symbol: "ETH",
    dripAmount: "0.05",
    cooldownHours: 24,
    explorer: "https://sepolia.etherscan.io",
    logoUrl: "/logos/eth.svg",
  },
  {
    id: "base",
    name: "Base Sepolia",
    type: "hotwallet",
    comingSoon: true,
    enabled: true,
    walletAddress: "0x528640F5c907e67714003dC9DF54D680F8F40E85",
    privateKeyEnv: "BASE_PRIVATE_KEY",
    rpcUrl: process.env.BASE_RPC_URL,
    chainId: 84532,
    symbol: "ETH",
    dripAmount: "0.05",
    cooldownHours: 24,
    explorer: "https://sepolia.basescan.org",
    logoUrl: "/logos/base.svg",
  },
  {
    id: "optimism",
    name: "Optimism Sepolia",
    type: "hotwallet",
    comingSoon: true,
    enabled: true,
    walletAddress: "0x9487df7d7108Eb56ae3f33370e630B7200cfceab",
    privateKeyEnv: "OPTIMISM_PRIVATE_KEY",
    rpcUrl: process.env.OPTIMISM_RPC_URL,
    chainId: 11155420,
    symbol: "ETH",
    dripAmount: "0.05",
    cooldownHours: 24,
    explorer: "https://sepolia-optimism.etherscan.io",
    logoUrl: "/logos/optimism.svg",
  },
  {
    id: "arbitrum",
    name: "Arbitrum Sepolia",
    type: "hotwallet",
    comingSoon: true,
    enabled: true,
    walletAddress: "0xe25eaFf8cA363A40a95D00536E3aB474266E680c",
    privateKeyEnv: "ARBITRUM_PRIVATE_KEY",
    rpcUrl: process.env.ARBITRUM_RPC_URL,
    chainId: 421614,
    symbol: "ETH",
    dripAmount: "0.05",
    cooldownHours: 24,
    explorer: "https://sepolia.arbiscan.io",
    logoUrl: "/logos/arbitrum.svg",
  },
  {
    id: "scroll",
    name: "Scroll Sepolia",
    type: "hotwallet",
    comingSoon: true,
    enabled: true,
    walletAddress: "0x54BF58beBc95fb46A344dfeEA12bC31433fEf69b",
    privateKeyEnv: "SCROLL_PRIVATE_KEY",
    rpcUrl: process.env.SCROLL_RPC_URL,
    chainId: 534351,
    symbol: "ETH",
    dripAmount: "0.05",
    cooldownHours: 24,
    explorer: "https://sepolia.scrollscan.com",
    logoUrl: "/logos/scroll.svg",
  },
  {
    id: "hoodi",
    name: "Hoodi",
    type: "hotwallet",
    comingSoon: true,
    enabled: true,
    walletAddress: "0xf6f8e90b49f79BB487bcb4e4c30B33C32f919382",
    privateKeyEnv: "HOODI_PRIVATE_KEY",
    rpcUrl: process.env.HOODI_RPC_URL,
    chainId: 560048,
    symbol: "ETH",
    dripAmount: "0.05",
    cooldownHours: 24,
    explorer: "https://hoodi.ethpandaops.io",
    logoUrl: "/logos/eth.svg",
  },

  // ─── API CHAINS ──────────────────────────────────────────────────────────
  {
    id: "polygon-amoy",
    name: "Polygon Amoy",
    type: "api",
    chainId: 80002,
    symbol: "POL",
    dripAmount: "0.5",
    explorer: "https://amoy.polygonscan.com",
    rpcUrl: process.env.POLYGON_AMOY_RPC_URL,
    faucetApi: "https://faucet.polygon.technology/api/faucet",
    logoUrl: "/logos/polygon.svg",
    enabled: true,
    comingSoon: false,
  },
  {
    id: "bnb-testnet",
    name: "BNB Testnet",
    type: "api",
    chainId: 97,
    symbol: "BNB",
    dripAmount: "0.1",
    explorer: "https://testnet.bscscan.com",
    rpcUrl: process.env.BNB_TESTNET_RPC_URL,
    faucetApi: "https://testnet.bnbchain.org/faucet-smart/api/claim",
    logoUrl: "/logos/bnb.svg",
    enabled: true,
    comingSoon: false,
  },
  {
    id: "avalanche-fuji",
    name: "Avalanche Fuji",
    type: "api",
    chainId: 43113,
    symbol: "AVAX",
    dripAmount: "0.5",
    explorer: "https://testnet.snowtrace.io",
    rpcUrl: process.env.AVAX_FUJI_RPC_URL,
    faucetApi: "https://api.avax-test.network/ext/bc/C/rpc",
    logoUrl: "/logos/avax.svg",
    enabled: true,
    comingSoon: false,
  },

  // ─── OTHER HOT WALLET CHAINS (coming soon) ───────────────────────────────
  {
    id: "genlayer",
    name: "GenLayer Testnet",
    type: "hotwallet",
    chainId: 961,
    symbol: "GEN",
    dripAmount: "1",
    explorer: "https://explorer.genlayer.com",
    rpcUrl: process.env.GENLAYER_RPC_URL,
    walletKey: process.env.GENLAYER_WALLET_KEY,
    logoUrl: "/logos/genlayer.svg",
    enabled: true,
    comingSoon: true,
  },
  {
    id: "arc",
    name: "ARC Testnet",
    type: "hotwallet",
    chainId: 10001,
    symbol: "USDC",
    dripAmount: "1",
    explorer: "https://explorer.arcology.network",
    rpcUrl: process.env.ARC_RPC_URL,
    walletKey: process.env.ARC_WALLET_KEY,
    logoUrl: "/logos/arc.svg",
    enabled: true,
    comingSoon: true,
  },
  {
    id: "zksync-sepolia",
    name: "zkSync Sepolia",
    type: "hotwallet",
    chainId: 300,
    symbol: "ETH",
    dripAmount: "0.05",
    explorer: "https://sepolia.explorer.zksync.io",
    rpcUrl: process.env.ZKSYNC_SEPOLIA_RPC_URL,
    walletKey: process.env.ZKSYNC_WALLET_KEY,
    logoUrl: "/logos/zksync.svg",
    enabled: true,
    comingSoon: true,
  },
  {
    id: "linea-sepolia",
    name: "Linea Sepolia",
    type: "hotwallet",
    chainId: 59141,
    symbol: "ETH",
    dripAmount: "0.05",
    explorer: "https://sepolia.lineascan.build",
    rpcUrl: process.env.LINEA_SEPOLIA_RPC_URL,
    walletKey: process.env.LINEA_WALLET_KEY,
    logoUrl: "/logos/linea.svg",
    enabled: true,
    comingSoon: true,
  },
  {
    id: "monad",
    name: "Monad Testnet",
    type: "hotwallet",
    chainId: 10143,
    symbol: "MON",
    dripAmount: "0.5",
    explorer: "https://testnet.monadexplorer.com",
    rpcUrl: process.env.MONAD_RPC_URL,
    walletKey: process.env.MONAD_WALLET_KEY,
    logoUrl: "/logos/monad.svg",
    enabled: true,
    comingSoon: true,
  },
];

// helpers
const getChain = (id) => chains.find((c) => c.id === id);
const getEnabledChains = () => chains.filter((c) => c.enabled);

module.exports = { chains, getChain, getEnabledChains };