const chains = [
  // ── GROUP B: API-based faucets ──────────────────────────────
  {
    id: "sepolia",
    name: "Ethereum Sepolia",
    type: "api",
    chainId: 11155111,
    symbol: "ETH",
    dripAmount: "0.05",
    explorer: "https://sepolia.etherscan.io",
    rpcUrl: process.env.SEPOLIA_RPC_URL,
    faucetApi: "https://api.alchemy.com/v2/faucet/sepolia",
    logoUrl: "/logos/eth.svg",
    enabled: true,
  },
  {
    id: "hoodi",
    name: "Ethereum Hoodi",
    type: "api",
    chainId: 560048,
    symbol: "ETH",
    dripAmount: "0.05",
    explorer: "https://hoodi.ethpandaops.io",
    rpcUrl: process.env.HOODI_RPC_URL,
    faucetApi: "https://faucet.quicknode.com/ethereum/hoodi",
    logoUrl: "/logos/eth.svg",
    enabled: true,
  },
  {
    id: "base-sepolia",
    name: "Base Sepolia",
    type: "api",
    chainId: 84532,
    symbol: "ETH",
    dripAmount: "0.05",
    explorer: "https://sepolia.basescan.org",
    rpcUrl: process.env.BASE_SEPOLIA_RPC_URL,
    faucetApi: "https://faucet.quicknode.com/base/sepolia",
    logoUrl: "/logos/base.svg",
    enabled: true,
  },
  {
    id: "op-sepolia",
    name: "Optimism Sepolia",
    type: "api",
    chainId: 11155420,
    symbol: "ETH",
    dripAmount: "0.05",
    explorer: "https://sepolia-optimism.etherscan.io",
    rpcUrl: process.env.OP_SEPOLIA_RPC_URL,
    faucetApi: "https://faucet.quicknode.com/optimism/sepolia",
    logoUrl: "/logos/op.svg",
    enabled: true,
  },
  {
    id: "arbitrum-sepolia",
    name: "Arbitrum Sepolia",
    type: "api",
    chainId: 421614,
    symbol: "ETH",
    dripAmount: "0.05",
    explorer: "https://sepolia.arbiscan.io",
    rpcUrl: process.env.ARB_SEPOLIA_RPC_URL,
    faucetApi: "https://api.alchemy.com/v2/faucet/arbitrum-sepolia",
    logoUrl: "/logos/arb.svg",
    enabled: true,
  },
  {
    id: "polygon-amoy",
    name: "Polygon Amoy",
    type: "api",
    chainId: 80002,
    symbol: "POL",
    dripAmount: "0.5",
    explorer: "https://amoy.polygonscan.com",
    rpcUrl: process.env.POLYGON_AMOY_RPC_URL,
    faucetApi: "https://faucet.polygon.technology/api/faucet",
    logoUrl: "/logos/polygon.svg",
    enabled: true,
  },
  {
    id: "bnb-testnet",
    name: "BNB Testnet",
    type: "api",
    chainId: 97,
    symbol: "BNB",
    dripAmount: "0.1",
    explorer: "https://testnet.bscscan.com",
    rpcUrl: process.env.BNB_TESTNET_RPC_URL,
    faucetApi: "https://testnet.bnbchain.org/faucet-smart/api/claim",
    logoUrl: "/logos/bnb.svg",
    enabled: true,
  },
  {
    id: "avalanche-fuji",
    name: "Avalanche Fuji",
    type: "api",
    chainId: 43113,
    symbol: "AVAX",
    dripAmount: "0.5",
    explorer: "https://testnet.snowtrace.io",
    rpcUrl: process.env.AVAX_FUJI_RPC_URL,
    faucetApi: "https://api.avax-test.network/ext/bc/C/rpc",
    logoUrl: "/logos/avax.svg",
    enabled: true,
  },
  {
    id: "scroll-sepolia",
    name: "Scroll Sepolia",
    type: "api",
    chainId: 534351,
    symbol: "ETH",
    dripAmount: "0.05",
    explorer: "https://sepolia.scrollscan.com",
    rpcUrl: process.env.SCROLL_SEPOLIA_RPC_URL,
    faucetApi: "https://api.alchemy.com/v2/faucet/scroll-sepolia",
    logoUrl: "/logos/scroll.svg",
    enabled: true,
  },

  // GenLayer
  {
    id: "genlayer",
    name: "GenLayer Testnet",
    type: "hotwallet",
    chainId: 961,
    symbol: "GEN",
    dripAmount: "1",
    explorer: "https://explorer.genlayer.com",
    rpcUrl: process.env.GENLAYER_RPC_URL,
    walletKey: process.env.GENLAYER_WALLET_KEY,
    logoUrl: "/logos/genlayer.svg",
    enabled: true,
    comingSoon: true,
  },
  // ARC
  {
    id: "arc",
    name: "ARC Testnet",
    type: "hotwallet",
    chainId: 10001,
    symbol: "USDC",
    dripAmount: "1",
    explorer: "https://explorer.arcology.network",
    rpcUrl: process.env.ARC_RPC_URL,
    walletKey: process.env.ARC_WALLET_KEY,
    logoUrl: "/logos/arc.svg",
    enabled: true,
    comingSoon: true,
  },
  {
    id: "zksync-sepolia",
    name: "zkSync Sepolia",
    type: "hotwallet",
    chainId: 300,
    symbol: "ETH",
    dripAmount: "0.05",
    explorer: "https://sepolia.explorer.zksync.io",
    rpcUrl: process.env.ZKSYNC_SEPOLIA_RPC_URL,
    walletKey: process.env.ZKSYNC_WALLET_KEY,
    logoUrl: "/logos/zksync.svg",
    enabled: true,
    comingSoon: true,
  },
  {
    id: "linea-sepolia",
    name: "Linea Sepolia",
    type: "hotwallet",
    chainId: 59141,
    symbol: "ETH",
    dripAmount: "0.05",
    explorer: "https://sepolia.lineascan.build",
    rpcUrl: process.env.LINEA_SEPOLIA_RPC_URL,
    walletKey: process.env.LINEA_WALLET_KEY,
    logoUrl: "/logos/linea.svg",
    enabled: true,
    comingSoon: true,
  },
  {
    id: "monad",
    name: "Monad Testnet",
    type: "hotwallet",
    chainId: 10143,
    symbol: "MON",
    dripAmount: "0.5",
    explorer: "https://testnet.monadexplorer.com",
    rpcUrl: process.env.MONAD_RPC_URL,
    walletKey: process.env.MONAD_WALLET_KEY,
    logoUrl: "/logos/monad.svg",
    enabled: true,
    comingSoon: true,
  },
];

// helper — get one chain by id
const getChain = (id) => chains.find((c) => c.id === id);

// helper — get all enabled chains
const getEnabledChains = () => chains.filter((c) => c.enabled);

module.exports = { chains, getChain, getEnabledChains };
